[package]
name = "pkcs"
version = "0.1.0"
edition = "2024"

[dependencies]
digest = "0.10.7"
eyre = "0.6.12"
hex = "0.4.3"
rsa = { version = "0.9.8", features = ["sha2"] }
sha2 = "0.10.8"
subtle = "2.6.1"
