[package]
name = "pss"
version = "0.1.0"
edition = "2024"

[dependencies]
# base64 = "0.22.1"
color-eyre = "0.6.3"
digest = { version = "0.10.7", features = ["alloc"] }
hex = "0.4.3"
rand = "0.9.0"
sha2 = "0.10.8"
subtle = "2.6.1"
